### PR TITLE
Attempt to address #120, _CONDA_SET_PROJ_LIB unsetting

### LINKED ISSUE #120: unbound variable _CONDA_SET_PROJ_LIB in deactivate.sh
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am getting the following error on my Azure DevOps Pipeline runs:

```
/usr/share/miniconda/envs/myenv/etc/conda/deactivate.d/proj4-deactivate.sh: line 5: _CONDA_SET_PROJ_LIB: unbound variable
```

The failing command is the conda install command that installs a package that depends on proj
Please use the same :- shell trick as in activate.sh

### Installed packages

```shell
Sorry for my ignorance, is conda-forge an upstream for this package?

  proj               pkgs/main/linux-64::proj-6.2.1-h05a3930_0
```

### Environment info

```shell
Azure Devops with vmImage="ubuntu-18.04"

Running bash CI-step:

conda create -y -n myenv python=3.7 conda-build
source $CONDA/bin/activate activate myenv
conda install -y PACKAGE_THAT_DEPENDS_ON_PROJ_VIA_OTHER_DEPENDENCY  <-- this command fails
```

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This attempts to address #120, but I'm not sure about the other deactivation scripts, so I only addressed bash. Please update as needed. 

closes #120

### CODE REVIEW

File: recipe/scripts/deactivate.sh [hunk 1]
```diff
@@ -5,6 +5,6 @@ unset PROJ_LIB
 unset PROJ_NETWORK
 
 if [ -n "$_CONDA_SET_PROJ_LIB" ]; then
-    export PROJ_LIB=$_CONDA_SET_PROJ_LIB
+    export PROJ_LIB="${_CONDA_SET_PROJ_LIB:-}"
```
Comment (xylar) [inline recipe/scripts/deactivate.sh]: I don't think this is the line that needs fixing.  It's the one above.
```suggestion
    export PROJ_LIB=$_CONDA_SET_PROJ_LIB
```

File: recipe/scripts/deactivate.sh [hunk 2]
```diff
@@ -5,6 +5,6 @@ unset PROJ_LIB
 unset PROJ_NETWORK
 
 if [ -n "$_CONDA_SET_PROJ_LIB" ]; then
```
Comment (xylar) [inline recipe/scripts/deactivate.sh]:
```suggestion
if [ -n "${_CONDA_SET_PROJ_LIB:-}" ]; then
```

**Comment by xylar** [comment]
> This attempts to address https://github.com/conda-forge/proj.4-feedstock/issues/120, but I'm not sure about the other deactivation scripts, so I only addressed bash. Please update as needed.

No one has reported a similar problem as in https://github.com/conda-forge/proj.4-feedstock/pull/100 for the other activation/deactivation scripts.  Maybe we assume they're fine unless someone can suggest the equivalent syntax for them?

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The errors are unrelated to the changes here:
```
Reading file '$SRC_DIR/test/gie/nkg.gie'
     -----
     FAILURE in nkg.gie(211):
     expected: 3275753.9111 321110.8658 5445041.8822 2020.0
     got:      3275753.909377121367   321110.862629641255   5445041.881752743   2020.000000000
     deviation:  3.635866 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(215):
     expected: 2391774.5535 615614.9100 5860965.8138 2020.0
     got:      2391774.548114618286   615614.906333823106   5860965.818464150   2020.000000000
     deviation:  8.012333 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(219):
     expected: 2107889.5097 895603.2085 5933242.3152 2020.0
     got:      2107889.501365525648   895603.205471481429   5933242.320781169   2020.000000000
     deviation:  10.477825 mm,  expected:  0.100000 mm
-------------------------------------------------------------------------------
total: 28 tests succeeded,  0 tests skipped,  3 tests FAILED!
-------------------------------------------------------------------------------
```
I'm not sure how the cropped up between #119 and now or what to do about them (other than report them upstream).

**Comment by xylar** [comment]
Looks like we need a patch: https://github.com/OSGeo/PROJ/pull/3106

**Comment by xylar** [comment]
@hobu, apologies for pushing changes to your branch.  I hope you don't mind.

**Comment by xylar** [comment]
@TormodLandet, do you want to have a look at this and make sure it fixes #120?

**Comment by TormodLandet** [comment]
Trying out the patched version:

```sh
set -euo pipefail  # enable shell strict mode
source deactivate.sh
```
results in

```
-bash: _CONDA_SET_PROJ_LIB: unbound variable
```

You need to change the if-statement to something like

```sh
if [ -n "${_CONDA_SET_PROJ_LIB:-}" ]; then
    export PROJ_LIB="${_CONDA_SET_PROJ_LIB}"
    unset _CONDA_SET_PROJ_LIB
fi
```

File: recipe/scripts/deactivate.sh [hunk 3]
```diff
@@ -4,7 +4,7 @@
 unset PROJ_LIB
 unset PROJ_NETWORK
 
-if [ -n "$_CONDA_SET_PROJ_LIB" ]; then
-    export PROJ_LIB=$_CONDA_SET_PROJ_LIB
+if [ -n "${_CONDA_SET_PROJ_LIB:-}" ]; then
+    export PROJ_LIB="${_CONDA_SET_PROJ_LIB}"
     unset _CONDA_SET_PROJ_LIB
 fi
```
Comment (xylar) [inline recipe/scripts/deactivate.sh:10]: @TormodLandet, I'm a little confused by why the previous version didn't work for you.  I think the problem was in the if, which I have not changed since last commit and is identical to what you requested.  I changed the `export` line to match your example.  See if this works as expected.

Comment (TormodLandet) [reply recipe/scripts/deactivate.sh:10]: I may have clicked on the wrong link, anyway the code in the PR now works

**Review by TormodLandet — APPROVED** [review]
Suggested solution works

**Comment by xylar** [comment]
Great, thanks!
